#!/usr/bin/sh
# Extract MySQL Error Code Definitions for the Windows


PATH=".:$PATH"

#Here we need to gather the  path to MySQL directory.
#TODO: Change it to use an ambient variable.
HDR1=$MYSQL_PATH/include/errmsg.h
HDR2=$MYSQL_PATH/include/mysqld_error.h

cat "$HDR1" "$HDR2" \
	| grep -v ERROR_LAST \
	| grep -v ERROR_FIRST \
	| sed -n '/^# *define *CR_[A-Za-z0-9_]* */p;/^# *define *ER_[A-Za-z0-9_]* */p' \
	| sed 's|/\*.*\*/||g;s| *$||' \
	| sed 's|# *define *||' \
	| while read NAME VALUE ; do
		echo "	{ \"$NAME\", $NAME },"
	done
	echo "#ifndef CR_NO_ERROR"
	echo "	{ \"CR_NO_ERROR\", 0 },"
	echo "#endif"
	echo "	{ 0, 0 }"

# End